### ISSUE TITLE
BY FEB ! Need to Be Able to add sticker numbers for Ramp Passes, Watercraft, and Dinghy

### ISSUE THREAD

**Issue by ABIRegistrar** [mattscilipoti/abi_registrar#24]
- Boat Ramp Access Pass: registration or Tag Number of the Boat or The Trailer and issued sticker number
- Watercraft Rack Storage Pass: description of the vessel, sticker number issued, beach number, rack slot number
- Dinghy Dock Storage Pass: description of the dinghy

**Comment by ABIRegistrar** [comment]
Please- read

https://www.ardenbeachesinc.com/order-my-stuff/registration-process

**Comment by mattscilipoti** [comment]
Can manage stickers for all amenities. Deployed.
