### ISSUE TITLE
Under the amenities - enable reissuing a sticker

### ISSUE THREAD

**Issue by ABIRegistrar** [mattscilipoti/abi_registrar#25]
Need to have a place under the persons information allowing for a check box that sticker was reissued, and a line availbble for me to add the new sticker number

**Comment by mattscilipoti** [comment]
We need to discuss reissuing. We will need to void the old sticker.
Do you need to see the voided stickers? From just this year?

**Comment by mattscilipoti** [comment]
Registrar has a process to void stickers (writing void in comments)
