### ISSUE TITLE
AMMENITIES PAID, AND PROCESSED (March 1)

### ISSUE THREAD

**Issue by ABIRegistrar** [mattscilipoti/abi_registrar#35]
I HAVE TO TRACK ONCE AMENITIES WHEN  PAID, AND THEN PROCESSED SENT OUT.

**Comment by mattscilipoti** [comment]
Add "Amenities Processed" boolean to Property. Allow toggle on Properties Index.

**Comment by mattscilipoti** [comment]
Deployed
