### ISSUE TITLE
CALENDAR VIEW- VS ENTERING DATES FOR RECEIVED PAYMENT UPDATES

### ISSUE THREAD

**Issue by ABIRegistrar** [mattscilipoti/abi_registrar#37]
NOW I HAVE TO SCROLL THE DATE.  CAN THIS DATE TO THE DEFAULT WHEN I GO INTO THE SYSTEM?   OR HAVE CALENDAR VIEW.  NOW I HAVE TO SCROLL TO THE YEAR, DATE ETC

**Comment by mattscilipoti** [comment]
Deployed
