### ISSUE TITLE
DEPENDENTS VS BOARDER

### ISSUE THREAD

**Issue by ABIRegistrar** [mattscilipoti/abi_registrar#49]
there is a transition age that after 21, dependents become boarders.   We should be asking for dependent birth year, and age.  We do not need exact birthday.   I need to have a place to record this information

**Comment by mattscilipoti** [comment]
From our earlier discussions, we felt we didn't need to record this information because we need to register/confirm /assign dependents, boarders, and renters each year and that info is on the jot form.
