### ISSUE TITLE
WHILE ENTERING STICKERS AND FINISH THE PROCESS,  CAN WE

### ISSUE THREAD

**Issue by ABIRegistrar** [mattscilipoti/abi_registrar#54]
HAVE A BUTTON THAT SAYS ENTER ANOTHER STICKER
FOR INSTANCE,  IF I'M ENTERING MULTIPLE CARS, OR STICKERS AT ONCE , I HAVE TO GO BACK TO THE CREATE SCREEN

**Comment by mattscilipoti** [comment]
Add this to all amenities.

**Comment by mattscilipoti** [comment]
Deployed
